<error errorId="0ee7b4bd-5ea2-455c-a08c-4e7b7ae88619" host="BLUECHIP-PC" type="System.Net.Sockets.SocketException" message="A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 159.122.224.201:443" source="System" detail="System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 159.122.224.201:443&#xD;&#xA;   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)&#xD;&#xA;   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext&amp; context)&#xD;&#xA;   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()&#xD;&#xA;   at SendGrid.Web.&lt;DeliverAsync&gt;d__7.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()&#xD;&#xA;   at TECIS.Web.Helpers.CrossCutting.SendGridEmailService.SendGridEmailService.&lt;SendGridMail&gt;d__a.MoveNext() in f:\LaoluOlapegba\MyMachine\MyDotnet\TECIS\TECIS.Web\Helpers\CrossCutting\EmailService\SendGridEmailService .cs:line 82&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()&#xD;&#xA;   at TECIS.Web.Controllers.ReportsController.&lt;GenGuestReport&gt;d__1e.MoveNext() in f:\LaoluOlapegba\MyMachine\MyDotnet\TECIS\TECIS.Web\Controllers\ReportsController.cs:line 532" user="laoluolapegba@gmail.com" time="2016-04-14T13:25:23.0390282Z" />